# Generated by Django 5.0.2 on 2024-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('trade_code', models.CharField(max_length=100, verbose_name='Trade Code')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('open', models.FloatField(verbose_name='Open')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.IntegerField(verbose_name='Volume')),
            ],
        ),
    ]
